---
title: "Project Code"
output: html_document
---

```{r hw3_setup, include=FALSE}
knitr::opts_chunk$set(echo=TRUE, eval=FALSE)
```

```{r}
library(tidymodels)
library(dplyr)
library(ggplot2)
library(rpart.plot)
library(tidymodels)
library(cluster)
library(kknn)
library(vip)
tidymodels_prefer()
flights <- read.csv("https://media.githubusercontent.com/media/yiyangshi-hub/STAT-253-Project/main/FlightData.csv")
```

# Classification

Reseach question: 

```{r}
flights_sub_c <- flights %>% 
  filter(ARR_DELAY_NEW > 0) %>%
  mutate(DEP_HOUR = round(as.numeric(DEP_TIME)/100)) %>%
  mutate(ARR_HOUR = round(as.numeric(ARR_TIME)/100)) %>%
  mutate(ARR_DELAY_LOG = log(ARR_DELAY_NEW)) %>%
  mutate(WEATHER = (WEATHER_DELAY > 5) & !is.na(WEATHER_DELAY)) %>%
  mutate(CARRIER = (CARRIER_DELAY > 5)&!is.na(CARRIER_DELAY)) %>%
  mutate(NAS = (NAS_DELAY > 5)&!is.na(NAS_DELAY)) %>%
  mutate(SECURITY = (SECURITY_DELAY > 5)&!is.na(SECURITY_DELAY)) %>%
  mutate(LATE_AIRCRAFT = (LATE_AIRCRAFT_DELAY > 5) &!is.na(LATE_AIRCRAFT_DELAY)) %>%
  mutate(arr_delay = ARR_DELAY_NEW > 10) %>%
  left_join(tibble(state.region,state.abb,state.division),by=c('ORIGIN_STATE_ABR' = 'state.abb')) %>%
  rename('ORIGIN_REGION' = state.region) %>%
  rename('ORIGIN_DIVISION' = state.division ) %>%  
  left_join(tibble(state.region,state.abb,state.division),by=c('DEST_STATE_ABR' = 'state.abb')) %>%
  rename('DEST_REGION' = state.region  ) %>%
  rename('DEST_DIVISION' = state.division ) %>% 
  select(-X,-(CARRIER_DELAY:LATE_AIRCRAFT_DELAY), -ARR_DEL15, -ORIGIN_STATE_ABR, -ORIGIN_STATE_NM, -DEST_STATE_ABR, -DEST_STATE_NM, -DEP_TIME, -ARR_TIME, -YEAR, -MONTH, -DAY_OF_MONTH, -OP_CARRIER_FL_NUM, -ORIGIN_DIVISION, -DEST_DIVISION, -ARR_DELAY_NEW, -ARR_DELAY_LOG) %>%
  mutate(arr_delay = factor(arr_delay),
         DAY_OF_WEEK = factor(DAY_OF_WEEK),
         ORIGIN = factor(ORIGIN),
         DEST = factor(DEST),
         WEATHER = factor(WEATHER),
         CARRIER = factor(CARRIER),
         NAS = factor(NAS),
         SECURITY = factor(SECURITY),
         LATE_AIRCRAFT = factor(LATE_AIRCRAFT),
         ORIGIN_REGION = factor(ORIGIN_REGION),
         DEST_REGION = factor(DEST_REGION),
         OP_CARRIER = factor(OP_CARRIER)) %>% 
  na.omit()
```

## 01 - Decision Tree
```{r}
set.seed(123)

flights_fold <- vfold_cv(flights_sub_c, v = 10)

flights_spec_tune <- decision_tree() %>%
  set_engine(engine = 'rpart') %>%
  set_args(cost_complexity = tune(),  
           min_n = 2, 
           tree_depth = NULL) %>% 
  set_mode('classification') 

flights_rec <- recipe(arr_delay ~ ., data = flights_sub_c)

flights_wf_tune <- workflow() %>%
  add_model(flights_spec_tune) %>%
  add_recipe(flights_rec)

param_grid <- grid_regular(cost_complexity(range = c(-5, 1)), levels = 10) 

tune_res <- tune_grid(
  flights_wf_tune, 
  resamples = flights_fold, 
  grid = param_grid, 
  metrics = metric_set(accuracy, sens, yardstick::spec, roc_auc)
)

autoplot(tune_res) + theme_classic()
```

```{r}
best_complexity <- select_by_one_std_err(tune_res, 
                                         metric ='accuracy',
                                         desc(cost_complexity))

flights_wf_final <- finalize_workflow(flights_wf_tune, best_complexity)

flights_final_fit <- fit(flights_wf_final, data = flights_sub_c)


tune_res %>% 
  collect_metrics() %>%
  filter(cost_complexity == best_complexity %>% pull(cost_complexity))
```

```{r}
tree_mod <- fit(
    flights_wf_tune %>%
      update_model(flights_spec_tune %>% 
                     set_args(cost_complexity = .001)),
    data = flights_sub_c
)

tree_mod %>% extract_fit_engine() %>% rpart.plot()
```


## 02 - Random Forest

```{r}
rf_spec <- rand_forest() %>%
  set_engine(engine = 'ranger') %>% 
  set_args(mtry = NULL, # size of random subset of variables; default is floor(sqrt(ncol(x)))
           trees = 50, # Number of bags
           min_n = 5000,
           probability = FALSE, # want hard predictions first
           importance = 'impurity') %>% 
  set_mode('classification') # change this for regression tree

rf_spec


flights_rf_wf <- workflow() %>%
  add_model(rf_spec) %>%
  add_recipe(flights_rec)
```


```{r}
set.seed(123)
flights_rf_fit <- flights_rf_wf %>%
  fit(data = flights_sub_c)

flights_rf_fit
```


```{r}
flights_rf_OOB_output <- tibble(
  .pred_class = flights_rf_fit %>% extract_fit_engine() %>% pluck('predictions'),
  arr_delay = flights_sub_c %>% pull(arr_delay))

bag_metrics <- metric_set(sens, yardstick::spec, accuracy)

flights_rf_OOB_output %>% 
  bag_metrics(truth = arr_delay, estimate = .pred_class)
```


### Soft Prediction
```{r}
set.seed(123) #to get the same bootstrap samples, use same seed
flights_rf_fit2 <- flights_rf_wf %>%
  update_model(rf_spec %>% set_args(probability = TRUE)) %>%
  fit(data = flights_sub_c)

flights_rf_fit2
```


### Variable Importance
```{r}
flights_rf_fit %>% extract_fit_engine() %>% vip() #based on impurity

flights_rf_wf %>% #based on permutation
  update_model(rf_spec %>% set_args(importance = "permutation")) %>%
  fit(data = flights_sub_c) %>% extract_fit_engine() %>% vip()
```

# CLustering

## 03 K-means
```{r}
set.seed(123)
flights_sub_k <- flights_sub %>% 
  sample_n(1000)

cust_cluster_sil <- function(k){
    # Perform clustering
    kclust <- pam(daisy(flights_sub_k), k = k)

    # Return the average silhouette
    return(kclust$silinfo$avg.width)
}

tibble(
    k = 2:15,
    tot_wc_ss = purrr::map_dbl(2:15, cust_cluster_sil)
) %>% 
    ggplot(aes(x = k, y = tot_wc_ss)) +
    geom_point() + 
    labs(x = "Number of clusters",y = 'Average Silhouette') + 
    theme_classic()
```

```{r}
set.seed(123)
kclust_k3_3vars <- kmeans(scale(daisy(flights_sub_k)), centers = 3)

# flights_sub_k3 <- flights_sub_k %>%
#     mutate(kclust_3_3vars = factor(kclust_k3_3vars$cluster))

flights_sub_k3 <- flights_sub_k %>%
  rename(Arrival_Delay=`arr_delay`, Region=`ORIGIN_REGION`)%>%
  select(Arrival_Delay, Region, DISTANCE, DAY_OF_WEEK, DEP_HOUR)

set.seed(123)
kclust <- pam(daisy(flights_sub_k3), k = 3)
kclust$cluster

flights_sub_k3 <- flights_sub_k3 %>%
    mutate(kclust_3 = factor(kclust$cluster))

ggplot(flights_sub_k3, 
       aes(fill= Arrival_Delay, x= Region)) +
  geom_bar(position='fill') +
  facet_wrap(~kclust_3)

ggplot(flights_sub_k3, 
       aes(x = DEP_HOUR,color = kclust_3))+
  geom_density()
```

