---
title: "Final Project V2.0"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidymodels)
tidymodels_prefer()

flights <- read.csv("https://media.githubusercontent.com/media/yiyangshi-hub/STAT-253-Project/main/FlightData.csv")
```

```{r}
flights_sub <- flights %>% 
  filter(ARR_DELAY_NEW > 0) %>%
  mutate(DEP_HOUR = round(as.numeric(DEP_TIME)/100)) %>%
  mutate(ARR_HOUR = round(as.numeric(ARR_TIME)/100)) %>%
  mutate(ARR_DELAY_LOG = log(ARR_DELAY_NEW)) %>%
  mutate(WEATHER = (WEATHER_DELAY > 5) & !is.na(WEATHER_DELAY)) %>%
  mutate(CARRIER = (CARRIER_DELAY > 5)&!is.na(CARRIER_DELAY)) %>%
  mutate(NAS = (NAS_DELAY > 5)&!is.na(NAS_DELAY)) %>%
  mutate(SECURITY = (SECURITY_DELAY > 5)&!is.na(SECURITY_DELAY)) %>%
  mutate(LATE_AIRCRAFT = (LATE_AIRCRAFT_DELAY > 5) &!is.na(LATE_AIRCRAFT_DELAY)) %>%
  left_join(tibble(state.region,state.abb,state.division),by=c('ORIGIN_STATE_ABR' = 'state.abb')) %>%
  rename('ORIGIN_REGION' = state.region) %>%
  rename('ORIGIN_DIVISION' = state.division ) %>%  
  left_join(tibble(state.region,state.abb,state.division),by=c('DEST_STATE_ABR' = 'state.abb')) %>%
  rename('DEST_REGION' = state.region  ) %>%
  rename('DEST_DIVISION' = state.division ) %>% 
  select(-X,-(CARRIER_DELAY:LATE_AIRCRAFT_DELAY), -ARR_DEL15) %>%
  #select(-X,-(CARRIER_DELAY:LATE_AIRCRAFT_DELAY), -ARR_DEL15, -ORIGIN_STATE_ABR, -ORIGIN_STATE_NM, -DEST_STATE_ABR, -DEST_STATE_NM, -DEP_TIME, -ARR_TIME, -YEAR, -MONTH, -DAY_OF_MONTH, -OP_CARRIER_FL_NUM, -ARR_DELAY_LOG) %>%
  mutate(DAY_OF_WEEK = factor(DAY_OF_WEEK),
         ORIGIN = factor(ORIGIN),
         DEST = factor(DEST),
         WEATHER = factor(WEATHER),
         CARRIER = factor(CARRIER),
         NAS = factor(NAS),
         SECURITY = factor(SECURITY),
         LATE_AIRCRAFT = factor(LATE_AIRCRAFT),
         ORIGIN_REGION = factor(ORIGIN_REGION),
         ORIGIN_DIVISION = factor(ORIGIN_DIVISION),
         DEST_REGION = factor(DEST_REGION),
         DEST_DIVISION = factor(DEST_DIVISION),
         OP_CARRIER = factor(OP_CARRIER)) %>% 
  na.omit()
```

```{r}
# If you do one train/test split 
data_split <- initial_split(flights_sub, strata = "ARR_DELAY_NEW", prop = 0.75) #Create Train/Test set
flights_train <- training(data_split) # Fit model to this
flights_test  <- testing(data_split) # Don't use until evaluating final model
```


# Linear Regression
```{r}
lm_spec <- 
  linear_reg() %>%  # Specify Model and Engine
  set_engine( engine = 'lm') %>%
  set_mode('regression') 

# rmse	standard	68.3753704		
# rsq	standard	0.2150813		
# mae	standard	26.6094113	
# lm_rec <- recipe(ARR_DELAY_NEW ~ DAY_OF_WEEK + OP_CARRIER + ORIGIN + DEST + DISTANCE + DEP_HOUR + ARR_HOUR + WEATHER + CARRIER + NAS + SECURITY + LATE_AIRCRAFT + ORIGIN_REGION + DEST_REGION, data = flights_train) %>%
#   step_lincomb(all_numeric_predictors()) %>% # Specify Formula and Preprocessing Recipe
#   step_zv(all_numeric_predictors()) %>%
#   step_dummy(all_nominal_predictors())


# rmse	standard	69.5591863		
# rsq	standard	0.1791365		
# mae	standard	25.6559957	
lm_rec <- recipe(ARR_DELAY_NEW ~ DAY_OF_WEEK + OP_CARRIER + DISTANCE + DEP_HOUR + ARR_HOUR + WEATHER + CARRIER + NAS + SECURITY + LATE_AIRCRAFT + ORIGIN_REGION + DEST_REGION, data = flights_train) %>%
  step_lincomb(all_numeric_predictors()) %>%
  step_zv(all_numeric_predictors()) %>%
  step_dummy(all_nominal_predictors())


# rmse	standard	69.8332401		
# rsq	standard	0.1812531		
# mae	standard	25.9948794	
# lm_rec <- recipe(ARR_DELAY_NEW ~ DAY_OF_WEEK + OP_CARRIER + DISTANCE + DEP_HOUR + ARR_HOUR + WEATHER + CARRIER + NAS + SECURITY + LATE_AIRCRAFT + ORIGIN_REGION + DEST_REGION + ORIGIN_DIVISION + DEST_DIVISION, data = flights_train) %>%
#   step_lincomb(all_numeric_predictors()) %>% # Specify Formula and Preprocessing Recipe
#   step_zv(all_numeric_predictors()) %>%
#   step_dummy(all_nominal_predictors())


train_prep <- lm_rec %>% 
  prep() %>%
  juice() # Pre-process Training Data

test_prep <- lm_rec %>%
  prep(training = flights_train) %>%
  bake(new_data = flights_test)


# Create Workflow (Recipe + Model Spec)
flights_wf <- workflow() %>% 
  add_recipe(lm_rec) %>%
  add_model(lm_spec)  


# Fit Model to Training Data
lm_fit_train <- flights_wf %>%
  fit(data = flights_train)  

# Calculate Training metrics
train_prep %>%
  select(ARR_DELAY_NEW) %>%
  bind_cols( predict(lm_fit_train, flights_train) ) %>% 
  metrics(estimate = .pred, truth = ARR_DELAY_NEW)  


lm_output <- train_prep %>%
  select(ARR_DELAY_NEW) %>%
  bind_cols( predict(lm_fit_train, flights_train) ) %>% 
  mutate(resid = ARR_DELAY_NEW - .pred)

# Model Coefficients from Trained Model
# lm_fit_train %>%
#   tidy() 
```


```{r}
ggplot(lm_output, aes(x = .pred, y = resid)) +
  geom_point() +
  geom_smooth() +
  geom_hline(yintercept = 0, color = "red") +
  labs(x = "Fitted values", y = "Residuals") +
  theme_classic()
```



```{r}
library(dotwhisker)
tidy(lm_fit_train) %>%  # Viz of Trained Model Coef
  dwplot(dot_args = list(size = 2, color = "black"),
         whisker_args = list(color = "black"),
         vline = geom_vline(xintercept = 0, color = "grey50", linetype = 2))
```


```{r}
# Create 10 Folds of Training Data for CV
flights_cv <- vfold_cv(flights_train, v = 10, strata = ARR_DELAY_NEW) 

# Fit Model to 10 Folds of Training Data
lm_fit_cv <- fit_resamples(flights_wf, 
              resamples = flights_cv,
              metrics = metric_set(rmse, mae, rsq))

# Evaluate Trained Model using CV
lm_fit_cv %>% collect_metrics() 

# emulates the process where, after determining the best model, the final fit on the entire training set is needed and is then evaluated on the test set.
lm_fit_test <- last_fit(flights_wf,
         split = data_split) 

# Evaluation on Test Data
lm_fit_test %>%
  collect_metrics() 
```


```{r}
library(vip)
conflicted::conflict_prefer("vi", "vip")

mod <- lm_fit_train %>% extract_fit_engine() 
vi(mod, method = 'permute', target = 'ARR_DELAY_NEW', metric = 'rmse', train = train_prep, pred_wrapper = predict)
vip(mod, method = 'permute', target = 'ARR_DELAY_NEW', metric = 'rmse', train = train_prep, pred_wrapper = predict) + theme_classic()
```



# Regularized Regression (LASSO)
```{r}
lm_lasso_spec <- 
  linear_reg() %>%
  set_args(mixture = 1, penalty = tune()) %>% 
  set_engine(engine = 'glmnet') %>%
  set_mode('regression') 

# Update Workflow (Recipe + Model Spec)
flights_wf <- flights_wf %>% 
  update_model(lm_lasso_spec)  

# Tune Model by Fitting Model to 10 Folds of Training Data
lasso_fit_cv <- tune_grid(flights_wf, 
              resamples = flights_cv,
              grid = 10,
              metrics = metric_set(rmse, mae, rsq))

lasso_fit_cv %>% autoplot() + theme_classic() # Evaluate Trained Model using CV
```


```{r}
# Select penalty value
lasso_fit_cv %>% show_best(metric = 'rmse')
best_penalty <- lasso_fit_cv %>% 
  select_by_one_std_err(metric = 'rmse',desc(penalty))

tuned_flights_wf <-  finalize_workflow(flights_wf,best_penalty)

# Save final tuned model spec
lm_lasso_spec <- tuned_flights_wf %>% pull_workflow_spec() 

# CV metrics
lasso_fit_cv %>% 
  collect_metrics() %>%
  filter(penalty == (best_penalty %>% pull(penalty))) 
```

```{r}
# Fit Tuned Lasso Model to Training Data
lasso_fit_train <- tuned_flights_wf %>%
  fit(data = flights_train)  

# Training metrics
train_prep %>%
  select(ARR_DELAY_NEW) %>%
  bind_cols( predict(lasso_fit_train, flights_train) ) %>% 
  metrics(estimate = .pred, truth = ARR_DELAY_NEW)  

# Model Coefficients from Trained Model
lasso_fit_train %>%
  tidy() 
```

```{r}
# lasso_fit_test <- last_fit(tuned_flights_wf, split = data_split)
# lasso_fit_test %>% 
#   collect_metrics()
```



```{r}
# Var Importance
glmnet_output <- lasso_fit_train %>% extract_fit_engine()
    
# Create a boolean matrix (predictors x lambdas) of variable exclusion
bool_predictor_exclude <- glmnet_output$beta==0

# Loop over each variable
var_imp <- sapply(seq_len(nrow(bool_predictor_exclude)), function(row) {
    this_coeff_path <- bool_predictor_exclude[row,]
    if(sum(this_coeff_path) == ncol(bool_predictor_exclude)){ return(0)}else{
    return(ncol(bool_predictor_exclude) - which.min(this_coeff_path) + 1)}
})

# Create a dataset of this information and sort
var_imp_data <- tibble(
    var_name = rownames(bool_predictor_exclude),
    var_imp = var_imp
)
var_imp_data %>% arrange(desc(var_imp))
```


# Nearest Neighbors
```{r}
knn_spec <- 
  nearest_neighbor() %>%
  set_args(neighbors = tune()) %>%
  set_engine(engine = 'kknn') %>%
  set_mode('regression') 

knn_rec <- recipe(ARR_DELAY_NEW ~ DAY_OF_WEEK + OP_CARRIER + DISTANCE + DEP_HOUR + ARR_HOUR + WEATHER + CARRIER + NAS + SECURITY + LATE_AIRCRAFT + ORIGIN_REGION + DEST_REGION, data = flights_train) %>% 
  step_normalize(all_numeric_predictors()) %>% 
  step_dummy(all_nominal_predictors())


knn_wf <- workflow() %>%
  add_model(knn_spec) %>% 
  add_recipe(knn_rec)

# Update Workflow (Recipe + Model Spec)
flights_wf <- flights_wf %>% 
  update_model(knn_spec)

penalty_grid <- grid_regular(
  neighbors(range = c(1, 50)), #  min and max of values for neighbors
  levels = 15) # number of neighbors values


# Tune Model by Fitting Model to 10 Folds of Training Data
knn_fit_cv <- tune_grid(flights_wf, 
              resamples = flights_cv,
              grid = 15,
              #grid = 20,
              metrics = metric_set(rmse, mae, rsq))

knn_fit_cv %>% autoplot() # Evaluate Trained Model using CV
```

```{r}
knn_fit_cv %>% show_best(metric = 'rmse')

best_neighbor <- knn_fit_cv %>% 
  select_by_one_std_err(metric = 'rmse', neighbors)

tuned_flights_wf <-  finalize_workflow(flights_wf, best_neighbor)

knn_spec <- tuned_flights_wf %>% pull_workflow_spec() # Save final tuned model spec


# CV Metrics
knn_fit_cv %>%
  collect_metrics() %>%
  filter(neighbors == (best_neighbor %>% pull(neighbors)))


# Fit KNN Model to Training Data
knn_fit_train <- tuned_flights_wf %>%
  fit(data = flights_train)  

train_prep %>%
  select(ARR_DELAY_NEW) %>%
  bind_cols( predict(knn_fit_train, flights_train) ) %>% 
  metrics(estimate = .pred, truth = ARR_DELAY_NEW)  # Training metrics

```

```{r}
knn_fit_test <- tuned_flights_wf %>%
  fit(data = flights_test)  

test_prep %>%
  select(ARR_DELAY_NEW) %>%
  bind_cols( predict(knn_fit_test, flights_test) ) %>% 
  metrics(estimate = .pred, truth = ARR_DELAY_NEW)  # test metrics
```


# GAM - Smoothing Splines
```{r}
gam_spec <- 
  gen_additive_mod() %>%
  set_engine(engine = 'mgcv') %>%
  set_mode('regression') 


gam_mod <- fit(gam_spec,
                ARR_DELAY_NEW ~ DAY_OF_WEEK + OP_CARRIER + s(DISTANCE) + s(DEP_HOUR) + s(ARR_HOUR) + WEATHER + CARRIER + NAS + SECURITY + LATE_AIRCRAFT + ORIGIN_REGION + DEST_REGION,
                data = flights_train)


par(mfrow=c(2,2))
gam_mod %>% pluck('fit') %>% mgcv::gam.check() 

gam_mod %>% pluck('fit') %>% summary()

gam_mod %>% pluck('fit') %>% plot( all.terms = TRUE, pages = 1)
```

```{r}
lm_spec <-
  linear_reg() %>%
  set_engine(engine = 'lm') %>%
  set_mode('regression')

flight_rec <- recipe(ARR_DELAY_NEW ~ DAY_OF_WEEK + OP_CARRIER + DISTANCE + DEP_HOUR + ARR_HOUR + WEATHER + CARRIER + NAS + SECURITY + LATE_AIRCRAFT + ORIGIN_REGION + DEST_REGION, data = flights_train)

spline_rec <- flight_rec %>%
     step_ns(DISTANCE, deg_free = 9) %>% 
     step_ns(DEP_HOUR, deg_free = 1) %>%
     step_ns(ARR_HOUR, deg_free = 9)

flight_wf <- workflow() %>%
    add_model(lm_spec) %>%
    add_recipe(flight_rec)

spline_wf <- workflow() %>%
    add_model(lm_spec) %>%
    add_recipe(spline_rec)
```

```{r}
fit_resamples(
    flight_wf,
    resamples = flights_cv,
    metrics = metric_set(mae,rmse,rsq)                     
) %>% collect_metrics()

GAM_fit_cv <- fit_resamples(
    spline_wf,
    resamples = flights_cv,
    metrics = metric_set(mae,rmse,rsq)                     
)
```





```{r}
fit_gam_model <- gam_spec %>% 
  fit(ARR_DELAY_NEW ~ DAY_OF_WEEK + OP_CARRIER + DISTANCE + DEP_HOUR + ARR_HOUR + WEATHER + CARRIER + NAS + SECURITY + LATE_AIRCRAFT + ORIGIN_REGION + DEST_REGION, data = flights_train)


# fit_gam_model <- gam_spec %>% 
#   fit(Sale_Price ~ Lot_Area + Year_Built +  House_Style + s(Gr_Liv_Area, k = 15) + Fireplaces, data = ames_train) 

# Summary: Parameter (linear) estimates and then Smooth Terms (H0: no relationship)
fit_gam_model %>% pluck('fit') %>% summary() 

# Diagnostics: Check to see if the number of knots is large enough (if p-value is low, increase number of knots)
par(mfrow=c(2,2))
fit_gam_model %>% pluck('fit') %>% mgcv::gam.check() 

# Visualize Non-Linear Functions
fit_gam_model %>% pluck('fit') %>% plot() 
```


# Regression Trees
```{r}
# tree_rec <- recipe(ARR_DELAY_NEW ~ DAY_OF_WEEK + OP_CARRIER + DISTANCE + DEP_HOUR + ARR_HOUR + WEATHER + CARRIER + NAS + SECURITY + LATE_AIRCRAFT + ORIGIN_REGION + DEST_REGION, data = flights_train) %>%
#   step_zv(all_numeric_predictors())

tree_spec <- 
  decision_tree() %>%
  set_engine(engine = 'rpart') %>%
  set_mode('regression') 


flights_wf <- flights_wf %>% # Update Workflow (Recipe + Model Spec)
  # update_recipe(tree_rec) %>%
  update_model(tree_spec)  

tree_fit_train <- flights_wf %>%
  fit(data = flights_train)  # Fit Reg Tree Model to Training Data

# Training metrics
train_prep %>%
  select(ARR_DELAY_NEW) %>%
  bind_cols( predict(tree_fit_train, flights_train) ) %>% 
  metrics(estimate = .pred, truth = ARR_DELAY_NEW)  

```

```{r}
tree_fit_train %>% 
  extract_fit_engine() %>% 
  rpart.plot::rpart.plot(roundint = FALSE)

tree_fit_cv <- flights_wf %>%
  fit_resamples(resamples = flights_cv,
                metrics = metric_set(rmse, mae, rsq))

tree_fit_cv %>%
  collect_metrics()
```



# Comparison of Methods

```{r}
lm_cv_result <- lm_fit_cv %>% 
  collect_metrics() %>%
  select(-n, -.config)

lm_cv_result$model <- 'OLS'
  

lassp_cv_result <- lasso_fit_cv %>% 
  collect_metrics() %>%
  filter(penalty == (best_penalty %>% pull(penalty))) %>% 
  select(-penalty, -n, -.config)

lassp_cv_result$model <- 'LASSO'


knn_cv_result <- knn_fit_cv %>%
  collect_metrics() %>%
  filter(neighbors == (best_neighbor %>% pull(neighbors))) %>% 
  select(-neighbors, -n, -.config)

knn_cv_result$model <- 'KNN'


GAM_cv_result <- GAM_fit_cv %>% 
  collect_metrics() %>% 
  select(-n, -.config)

GAM_cv_result$model <- 'GAM'

tree_cv_result <- tree_fit_cv %>%
  collect_metrics() %>% 
  select(-n, -.config)

tree_cv_result$model <- 'Tree'
```

```{r}
model_summary <- rbind(lm_cv_result, lassp_cv_result, knn_cv_result, GAM_cv_result, tree_cv_result) %>% 
  select(model, .metric, .estimator, mean, std_err)
```



```{r}
model_summary %>% 
  ggplot(aes(x = model, y = mean)) +
  geom_point() +
  geom_errorbar(aes(ymin = mean-std_err, ymax = mean+std_err), width = .2,
                position = position_dodge(0.05))+
  facet_wrap(~.metric, scales = "free")
```



```{r}
wf_set <- workflow_set(
  preproc = list(lm = lm_rec, tree = tree_rec),
  models = list(lm = lm_spec, lasso = lm_lasso_spec, knn = knn_spec, tree = tree_spec),
  cross = TRUE) %>% 
   anti_join(tibble(wflow_id = c("lm_tree","spline_lasso", "spline_knn","spline_tree","tree_lm","tree_lasso","tree_knn")), 
             by = "wflow_id")

flights_wf_set <- wf_set %>%
  workflow_map(
    "fit_resamples", 
    resamples = flights_cv, # Compare Methods via CV
    metrics = metric_set(rmse, rsq, mae)) 
    
flights_wf_set %>% autoplot()
flights_wf_set %>% rank_results(rank_metric = 'rmse')
```






